spring:
  application:
    name: edu-admin-management
  datasource:
    url: jdbc:mysql://8.163.40.230:3306/edu_admin?serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edu_admin
    password: paidZzjwHNGxRmTp
  redis:
    host: 8.163.40.230
    port: 6379
    database: 0
    timeout: 3000ms

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug